apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleprojectdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sampleprojectdemo
  template:
    metadata:
      labels:
        app: sampleprojectdemo
    spec:
      containers:
      - name: R1repos
        image: SampleCR.azurecr.io/R1repos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: sampleprojectdemosn

---
apiVersion: v1
kind: Service
metadata:
  name: dockersampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Dockersampleconfig
