apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleprojectdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SampleProjectDemo
  template:
    metadata:
      labels:
        app: SampleProjectDemo
    spec:
      containers:
      - name: sampleprojectdemo
        image: samplecr.azurecr.io/r1repos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: sampleprojectdemosn

---
apiVersion: v1
kind: Service
metadata:
  name: sampleprojectdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: SampleProjectDemo
